export const loginRoute = "/auth/login";
export const registerRoute = "/auth/register";
export const logoutRoute = "/auth/logout";
export const userInfoRoute = "/user/me";
export const getAllProducts = "/product/all";
export const getOneProduct = (id) => `/product/${id}`;
export const addProduct = "/product/add";
export const removeProduct = "/product/remove";
export const sellerAddProduct = "/seller/products";
export const sellerUpdateProduct = (id) => `/seller/products/${id}`;
export const sellerDeleteProduct = (id) => `/seller/products/${id}`;
export const paymentRoute = "/payment/create";
export const orderRoute = "/order";
